import "./globals.css"
import { dmSans } from "@/fonts"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.className} h-full antialiased bg-black text-white`}
      suppressHydrationWarning
    >
      <body className="min-h-full w-full flex flex-col bg-black text-white">{children}</body>
    </html>
  )
}
